# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.5

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - name: config
              command: >-
                echo "export const API = { SERVER_URL: 'http://ap.edumall.vn:8080', };" >> config/config-production.js
            - npm install
            - npm run deploy:prod
            - scp -rf ./dist/* $SERVER_DIST
